### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [app-academy-exercises-jb/YASC#3]
- [x] users need a first name and last name and display name
- [x] sessions table (session belongs to a user)
- [x] has_many :memberships, as: :membershipable
- [x] has_many :users, through: :memberships, source: :user
- [x] remove owner_id from channels
- [x] reply_id on a messages
- [x] one user should only have one membership to a membershipable item

**Comment by ssoonmi** [comment]
Please make the above changes in your wiki page

**Comment by jorge-barreto** [comment]
- [x] :messages has_many :replies
