### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ssoonmi** [app-academy-exercises-jb/YASC#6]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

Please Slack me when you complete all these.

**Comment by ssoonmi** [comment]
### Changes to Make

- [ ] Form for signing up should closer to the top
- [ ] Form for signing up has a shading around it
- [ ] Form for logging in has a bolder bottom
- [ ] Header and Button font is a little too bold (looks like your font is naturally a bit bolder than the one in actual Slack)
- [ ] Need to style the nav bar and greeting when you are logged in
- [ ] Spacing for the sides of the nav bar and its content should be fixed (not variable to size of device)

**Comment by jorge-barreto** [comment]
- [ ] login page box should be wider: consult slack

**Comment by ssoonmi** [comment]
- [ ] need to display errors in an appealing way, similar to: 
![Screen Shot 2020-03-04 at 11 46 40 AM](https://user-images.githubusercontent.com/40774865/75943098-ef14de80-5e48-11ea-98be-f9251ba348b4.png)

Awesome work so far! :)

**Comment by ssoonmi** [comment]
- [ ] In `seeds.rb`, should be `User.create!` (with a `!`)
