### ISSUE TITLE
Workspaces Review

### ISSUE THREAD

**Issue by ssoonmi** [app-academy-exercises-jb/YASC#7]
# Workspaces

## Functionality

- [x] Smooth, bug free navigation

### Workspace Creation
- [x] Logged in Users can create a new workspace at `/create`

### Editing a Workspace
- [x] Users can edit their own workspace at `/workspaces/:workspaceId/edit`
- [ ] (optional) can add an icon to the workspace with AWS S3 integration
- [x] Users can delete their own workspace

### Join Existing Workspace
- [x] can find an existing workspace to join at `/add`

### Viewing workspaces
- [x] Users can view all their workspaces at `/app` on the side bar
- [x] Users can view a workspace they are part of at `/app/:workspaceId`

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have cursor: pointer on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds

- [ ] Adequate and appropriate seeds

**Comment by jorge-barreto** [comment]
__TODO__

- [ ] should be no margin change between `/create` and `/create/channelname`
- [ ] create workspaces page needs errors
- [ ] workspaces dropdown needs workspaces
- [ ] need an `/admin` page where user can make edits to self + workspaces
- [ ] `/find` needs its "try another login" link to logout -> redirect to login
- [ ] `/find` needs content when user has no current workspaces

**Comment by ssoonmi** [comment]
- [ ] not sure if this is necessary or not, but the `/app` feature should be scaled down in size compared to actual Slack
- [ ] workspace id should be changing in the URL path when switching between workspaces
- [ ] should have a confirmation for deleting a workspace

There seems to be an admin page dedicated to just a single workspace. Not sure if you want to implement that in this feature but what you have currently is fine. 

Love it! Great job on the hover effects!
